### ISSUE TITLE
[PATCH] Update POD to reflect that -verbose => 0 shows SYNOPSIS|USAGE [rt.cpan.org #133242]

### ISSUE THREAD

**Issue by atoomic** [Dual-Life/Pod-Usage#5]
Migrated from [rt.cpan.org#133242](https://rt.cpan.org/Ticket/Display.html?id=133242) (status was 'new')

Requestors:
* ernstki@mail.uc.edu

Attachments:
* [synopsis_and_or_usage.patch](https://rt.cpan.org/Ticket/Attachment/1909948/1023090/synopsis_and_or_usage.patch)

From ernstki@mail.uc.edu on 2020-08-28 13:23:08
:
```
Hi Marek,

It seems that POD sections entitled "SYNOPSIS" *or* "USAGE" are included with 'pod2usage(-verbose => 0)', yet there is no mention of "USAGE" in the documentation.

The included patch (apply with 'patch -p1') makes the necessary correction to the Pod::Usage POD.

This is my first patch to any CPAN library, so I am open to coaching or any constructive criticism.

Cheers,
Kevin

```

**Comment by ernstki** [comment]
Thank you, sir!
